version: '2'

services:
  certs:
    build: build/certs
    env_file: docker-compose.env
    volumes:
      - ./data/ssl:/etc/ssl

  haraka:
    build: build/haraka
    restart: unless-stopped
    ports:
      - '25:25'
      - '465:465'
      - '587:587'
    volumes:
      - ./data/haraka:/app/outbound
      - ./data/mail:/var/mail
    volumes_from:
      - data

  mariadb:
    image: mariadb
    restart: unless-stopped
    env_file: docker-compose.env
    volumes:
      - ./data/mariadb:/var/lib/mysql

  mariadb-admin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    env_file: docker-compose.env
    depends_on:
      - mariadb
    # ports:
    #   - "8000:80"

  dovecot:
    build: build/dovecot
    restart: unless-stopped
    env_file: docker-compose.env
    links:
      - mariadb
    depends_on:
      - certs
      - mariadb
    ports:
    # POP3
     - '110:110'
     - '995:995'
    # IMAP
     - '143:143'
     - '993:993'
    # SMTP SSL: Submission
    #  - '587:587'
    # LMTP
     - '24:24'
    # ManageSieve
     - '4190:4190'
    volumes:
      - ./data/mail:/var/mail
    volumes_from:
      - data

  # postgres-admin:
  #   image: adminer
  #   restart: unless-stopped
  #   env_file: docker-compose.env
  #   # ports:
  #   #  - '8080:8080'

  # roundcube:
  #   image: roundcube/roundcubemail:1.4.x-apache
  #   restart: unless-stopped
  #   env_file: docker-compose.env
  #   # ports:
  #   #   - "80:80"
  #   links:
  #     - postgres
  #   depends_on:
  #     - certs
  #     - postgres
  #   volumes_from:
  #     - data

  # mailadmin:
  #   build: build/postfixadmin
  #   # image: postfixadmin:3
  #   restart: unless-stopped
  #   env_file: docker-compose.env
  #   links:
  #     - postgres
  #   depends_on:
  #     - certs
  #     - postgres
  #   # ports:
  #   #   - "80:80"

  data:
    image: node:10-alpine
    command: echo "Done."
    volumes:
      - ./data/ssl:/etc/ssl:ro
      - ./data/tmp:/tmp

# create network: docker network create xnmp-network
networks:
  default:
    external:
      name: xnmp-network